version: '3.9'

services:

  # Private-GPT service for the Ollama CPU and GPU modes
  private-gpt-ollama:
    user: root
    image: ${PGPT_IMAGE:-zylonai/private-gpt}:${PGPT_TAG:-0.6.2}-ollama
    build:
      context: .
      dockerfile: Dockerfile.ollama
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
      PGPT_EMBED_MODE: ollama
      PGPT_OLLAMA_API_BASE: http://ollama:11434
      HF_TOKEN: ${HF_TOKEN:-}
    profiles:
      - ""
      - ollama-cpu      
      - ollama-api
    depends_on:
      - ollama
    networks:
      - ollama-net

  # Private-GPT service for the local mode
  private-gpt-llamacpp-cpu:
    image: ${PGPT_IMAGE:-zylonai/private-gpt}:${PGPT_TAG:-0.6.2}-llamacpp-cpu
    build:
      context: .
      dockerfile: Dockerfile.llamacpp-cpu
    volumes:
      - ./local_data/:/home/worker/app/local_data
      - ./models/:/home/worker/app/models
    entrypoint: sh -c ".venv/bin/python scripts/setup && .venv/bin/python -m private_gpt"
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      PGPT_PROFILES: ollama
      HF_TOKEN: ${HF_TOKEN}
    profiles:
      - llamacpp-cpu
    networks:
      - ollama-net

  # Traefik reverse proxy for the Ollama service
  traefik:
    image: traefik:v2.10
    ports:
      - "8081:8080"
      - "11434:11434"  # Exposing port 11434 for Ollama
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:11434"
      - "--api.insecure=true"
      - "--log.level=ERROR"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ollama-net

  # Ollama service
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./models:/root/.ollama
    networks:
      - ollama-net

  # Ollama service for CUDA mode
  ollama-cuda:
    image: ollama/ollama:latest
    volumes:
      - ./models:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    profiles:
      - ollama-cuda
    networks:
      - ollama-net

networks:
  ollama-net:
    driver: bridge
